### ISSUE TITLE
Logo creation

### ISSUE THREAD

**Issue by Qkessler** [Qkessler/CloudQuestions#35]
CloudQuestions currently doesn't have a logo! Feel free to submit all work, it will be greatly appreciated.

**Comment by juanoa** [comment]
Feel free to use or modify it.

<img width="1087" alt="Recurso 1@2x" src="https://user-images.githubusercontent.com/19978031/91156387-64f55680-e6c4-11ea-8b22-506cae75f98b.png">

**Comment by Qkessler** [comment]
Thank you so much! This is great! Would be awesome if you could also send a white version so I can add it to the landing page!
Will keep the issue open until I merge all into master! Great work!

**Comment by juanoa** [comment]
Yes, I attach the vectorized logo and 2 .png (W&B)
[cq-logo.zip](https://github.com/Qkessler/CloudQuestions/files/5128480/cq-logo.zip)
